services:
  - type: web
    name: comparekart-backend
    env: docker
    plan: starter
    rootDir: backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: smart_price_comparator
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE_MINUTES
        value: "10080"
